import { useEffect } from "react";

const portfolioItems = ['HTML', 'CSS', 'JS', 'React', 'GSAP', 'Three.js'];

export default function PortfolioSection() {
  useEffect(() => {
    const carousel = document.getElementById('carousel3d');
    if (carousel) {
      const radius = 150;
      const angleStep = (2 * Math.PI) / portfolioItems.length;

      portfolioItems.forEach((item, i) => {
        const div = document.createElement('div');
        div.className = 'carousel-item';
        div.textContent = item;
        
        const angle = i * angleStep;
        const x = Math.cos(angle) * radius;
        const z = Math.sin(angle) * radius;
        
        div.style.transform = `translate3d(${x}px, -150px, ${z}px) rotateY(${angle}rad)`;
        carousel.appendChild(div);
      });
    }
  }, []);

  return (
    <section id="portfolio" className="min-h-screen py-20 px-8">
      <div className="max-w-6xl mx-auto">
        <h2 
          className="text-gradient text-6xl font-bold text-center mb-12"
          style={{ fontFamily: "'Orbitron', sans-serif" }}
        >
          Portfolio 3D
        </h2>
        
        <div className="carousel-3d mt-12">
          <div className="carousel-container" id="carousel3d">
            {/* 3D carousel items will be generated by useEffect */}
          </div>
        </div>
      </div>
    </section>
  );
}
